version: '3.8'

services:
    web:
        build: ./
        command: gunicorn --workers=5 app:app --bind 0.0.0.0:3000
        volumes:
            - ./:/usr/src/app/
        ports:
            - 3000:3000
