version: '3.8'

services:
    web:
        build: ./
        command: gunicorn -w 5 -b 0.0.0.0:3000 -k eventlet -n lugaapp app:app
        volumes:
            - ./:/usr/src/app/
        ports:
            - 3000:3000
